### ISSUE TITLE
Make `iceoryx2-bb-container` public API

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx2#176]
## (Code) Example Of Cumbersome API

For more advanced data types, those crates become necessary. Therefore, it should be a public API. 

## ToDo

* [x] Complete developer documentation
* [x] Add doc examples for all use cases
* [x] Check test coverage
* [x] All error enums must implement `std::error::Error` 
* [x] Adjust `complex_data_type` example
