### ISSUE TITLE
Create C++ language binding

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx2#264]
## Brief feature description

Create a `C++` language binding for the iceoryx2 public API.

## Detailed information

Based on the `C` language binding from #210, a `C++` binding should be created in order to make iceoryx2 available to the `C++` ecosystem.

## ToDo List

* [ ] Remove all `IOX_TODO()` calls.

### Examples

* [x] complex_data_types
* [x] discovery
* [x] event
* [x] publish_subscribe
* [x] publish_subscribe_dynamic_data
* [x] publish_subscribe_with_user_header
* [x] service_attributes
* [ ] main readme updated

### Classes

* [x] attribute.hpp
* [x] attribute_set.hpp
* [x] attribute_specifier.hpp
* [x] attribute_verifier.hpp
* [x] callback_progression.hpp
* [x] config.hpp
* [x] connection_failure.hpp
* [ ] dynamic_config_event.hpp
* [ ] dynamic_config_publish_subscribe.hpp
* [x] event_id.hpp
* [x] header_publish_subscribe.hpp
* [x] listener.hpp
* [x] message_type_details.hpp
* [x] messaging_pattern.hpp
* [x] node_details.hpp
* [x] node_failure_enums.hpp
* [ ] node.hpp
* [x] node_id.hpp
* [x] node_name.hpp
* [x] node_state.hpp
* [x] notifier.hpp
* [ ] port_factory_event.hpp
* [x] port_factory_listener.hpp
* [x] port_factory_notifier.hpp
* [ ] port_factory_publisher.hpp
* [ ] port_factory_publish_subscribe.hpp
* [x] port_factory_subscriber.hpp
* [ ] publisher.hpp
* [x] sample.hpp
* [ ] sample_mut.hpp
* [x] semantic_string.hpp
* [ ] service_builder_event.hpp
* [x] service_builder.hpp
* [ ] service_builder_publish_subscribe.hpp
* [ ] service_details.hpp
* [ ] service.hpp
* [x] service_name.hpp
* [x] service_type.hpp
* [x] static_config_event.hpp
* [ ] static_config.hpp
* [x] static_config_publish_subscribe.hpp
* [ ] subscriber.hpp
* [x] unique_port_id.hpp

**Comment by mossmaurice** [comment]
@elfenpiff Is this issue already completed? According to the issue description a few API calls are still missing.

**Comment by elfenpiff** [comment]
@mossmaurice thanks for the hint ... yes there are still some tiny bits and pieces missing.
