### ISSUE TITLE
Add clang-format and clang-tidy for C and C++ language bindings

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx2#265]
## Brief feature description

Add a `.clang-format` and a `.clang-tidy` file to the repository root.

## Detailed information

The files should be based on the ones from the `eclipse-iceoryx/iceoryx` repo but can be adjusted to match the formatting of `rustfmt` more closely.

## Tasks

- [x] add a `.clang-format` file
  - based on the one from iceoryx1 but maybe adjusted to mimic the `rustfmt` formatting more closely
- [x] add a `.clang-tidy` file
  - also based on the ton from iceoryx1 
- [x] CI check for `clang-tidy` and `clang-format`
