### ISSUE TITLE
ROS2-like CLI for iceoryx2

### ISSUE THREAD

**Issue by orecham** [eclipse-iceoryx/iceoryx2#98]
## Brief feature description

A ROS2-like CLI enabling users to interact with `iceoryx2` from the terminal would be a useful addition for users to aid development of applications. 

## Detailed information

An summary of the capabilities of the ROS 2 CLI can be found [here](https://github.com/ubuntu-robotics/ros2_cheats_sheet/blob/master/cli/cli_cheats_sheet.pdf). NOTE: The `iceoryx2` does not need to necessarily provide all of the same functionality, this should just be taken as inspiration for what could be useful.

Proposal for initial for CLI functionality:

1. `introspect` - introspect the internals of the `iceoryx2` system (e.g. things stored in shared memory)
1. `processes` - manage processes running `iceoryx2` 
1. `pub` - publish to the `iceoryx2` system from the terminal
1. `rpc` - execute `iceoryx2` rpc operations from the terminal
1. `services` - manage the services currently available in `iceoryx2`
1. `sub` - subscribe to the `iceoryx2` system from the terminal

## Tasks

Follow up from #106:
1. [x] Address TODOs in commands.rs
1. [x] Ensure implementation of commands.rs follows Rust conventions
1. [x] Display installed commands before development commands
1. [x] Work out how to test command lookup in file system
1. [x] Add `iceoryx2-cli` to `internal/scripts/crates_io_publish_script.sh` to release it.

Follow up from #371:
1. [ ] Factor out CLI setup into common lib: https://github.com/eclipse-iceoryx/iceoryx2/pull/371#discussion_r1766353301

**Comment by orecham** [comment]
Tasks:

1. [ ] Ensure implementation of `commands.rs` follows Rust conventions
2. [ ]

**Comment by elBoberido** [comment]
@orecham can you add those items directly as tasks to the issue description?

**Comment by orecham** [comment]
> @orecham can you add those items directly as tasks to the issue description?

@elBoberido Done

**Comment by orecham** [comment]
@elBoberido @elfenpiff I would like to close this issue now that we have the foundation for the CLI tooling. What do you think?

We can add new issues as we think of use-cases. I can only think of one more obvious one at the moment (memory introspection, maybe an `iox2 memory` command.

I would also make this open action item a separate issue: `Factor out CLI setup into common lib`

**Comment by elBoberido** [comment]
@orecham agreed, go ahead
